### ISSUE TITLE
tinydtls won't install on macOS without modifications

### ISSUE THREAD

**Issue by morberg** [ggravlingen/pytradfri#64]
When trying to install tinydtls from `git clone --depth 1 https://git.fslab.de/jkonra2m/tinydtls.git` on macOS 10.12 it will fail with:

`../mc-helper.c:82:35: error: use of undeclared identifier 'IPV6_ADD_MEMBERSHIP'
  if(setsockopt(fd, IPPROTO_IPV6, IPV6_ADD_MEMBERSHIP, &mreq, sizeof(mreq))){`

It seems `IPV6_ADD_MEMBERSHIP` is deprecated and `IPV6_JOIN_GROUP` should be used instead (I am way out of my depth here and might be very wrong).

Replacing the three mentions of `IPV6_ADD_MEMBERSHIP` with `IPV6_JOIN_GROUP` in `mc-helper.c` makes it possible to install tinydtls on macOS and tradfri seems to work fine in Home Assistant 0.55.0.

(I also did `mv configure.in configure.ac` to get rid of a warning from `autoconf`.)

**Comment by lwis** [comment]
@morberg could you approach jkonra2m to discuss the issue further, or update the README here with macOS instructions please?

**Comment by morberg** [comment]
I couldn't link my github account to the gitlab installation where jkonra2m has his tinydtls implementation to submit an issue there. I *think* jkonra2m is @kabel42 here on github. I'll try to get hold of him to discuss further.

**Comment by diplix** [comment]
can confirm what @morberg says, replacing mentions of `IPV6_ADD_MEMBERSHIP` works with macos 10.11.6 (el capitan), too. altough tinydtls was present and compiled (and worked fine in HA 0.54.0), i had to recompile it after installation of HA 0.55.0.

**Comment by kabel42** [comment]
Hi,
the Repo https://git.fslab.de/jkonra2m/tinydtls.git is for experiments with multicast DTLS could you try if https://git.fslab.de/jkonra2m/tinydtls-cython works for you? You can also get that one on pypi: https://pypi.python.org/pypi/DTLSSocket/0.1.3

**Comment by morberg** [comment]
I'm not familiar with the history of this project, but it might be that Tradfri needs multicast DTLS. I have seen one mention of the [Android Tradfri app using multicast DTLS to find the gateway](https://github.com/bwssytems/ha-bridge/issues/570#issuecomment-291447382).

Perhaps @ggravlingen or @lwis know if multicast is needed or if the pypi version would be enough?

**Comment by lwis** [comment]
I'm 95% sure we don't need multicast, so we can probably switch to https://git.fslab.de/jkonra2m/tinydtls-cython

**Comment by ggravlingen** [comment]
I just read a use case for multicast and it didn't quite seem to apply to Tradfri so I'm prone to agree with @lwis. @morberg are you able to do a test using https://git.fslab.de/jkonra2m/tinydtls-cython?

**Comment by balloob** [comment]
Ooh, if we can use DTLSSocket from PyPi, that would be the best.

I am able to install DTLSSocket on my Mac after I installed the cython package. However, I think that this would also require an update to aiocoap to use DTLSSocket instead of plain tinydtls?

**Comment by lwis** [comment]
Looks like it already uses it https://github.com/chrysn/aiocoap/search?utf8=%E2%9C%93&q=DTLSSocket

**Comment by balloob** [comment]
ooh, we should install aiocoap[tinydtls] and it will include the tinydtls dependency. I wonder if we can specify that as a dependency in our setup.py?

**Comment by lwis** [comment]
I think we can switch our extras to reference an extra? 

https://github.com/ggravlingen/pytradfri/blob/master/setup.py#L8

I'll play around with it later, may also mean we don't have to do the aiocoap patch.

**Comment by lwis** [comment]
We no longer need to install tinydtls in this way, as we use DTLSSocket which doesn't have the same problem.
